root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main -e=develop"
  cmd = "go build -o ./tmp/main ."
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor"]
  # Exclude files.
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  # Customize binary.
  # full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  # Debug
  full_bin = "APP_ENV=dev APP_USER=air  exec ./tmp/main --headless=true --listen=:2345 --api-version=2 --accept-multiclient"
  # Watch these directories if you specified.
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Delay after sending Interrupt signal
  kill_delay = 500 # ms
  # This log file places in your tmp_dir.
  log = "air.log"
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Stop running old binary when build errors occur.
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = false

[misc]
# Delete tmp directory on exit
clean_on_exit = true